유어링크 크롬익스텐션 팝업창 개선
urLink-DEV/urLink-frontend pull request #153
Opened 2021-07-17 14:45 UTC by anxiubin

## 유어링크 크롬익스텐션 팝업창 개선
- 팝업창 최상단에 카테고리 생성 버튼 추가
- 디자인은 기존 유어링크에 있는 카테고리 생성 버튼과 동일
- `ok 버튼`을 누르거나 input에 focus 되어있을 때 `enter 키`를 누르면 추가되는 로직

2021-07-19 13:36 UTC, yjkwon07 reviewed
- 단일 원칙 책임으로, 부가적인 기능을 많이 피하는게 좋을거 같아요.
- 해당 APILoad Object에서 categoryCreate, linkWrite 함수는 EventListener에서 관리하는게 맞는거 같네요.

2021-07-19 13:36 UTC, yjkwon07 commented on src/popup/index.js
> +          categoryCreateInputWrapperElement +
- categoryCreateButtonElement, categoryCreateInputWrapperElement 고정적인 element일 경우,  index.html에서 정의하는게 어떨까요?
- js 불러올 때, 보다 index.html 불러올 때 돔을 그려주는게 더 좋아보입니다.
  - 다른 특별한 이유가 있나요?

2021-07-19 13:36 UTC, yjkwon07 commented on src/popup/index.js
> +          categoryCreateButtonElement + categoryCreateInputWrapperElement + Template.categoryEmpty()
- 위의 상황과 같은 의견입니다. (index.html)

2021-07-19 13:36 UTC, yjkwon07 commented on src/popup/index.js
> +          APILoad.categoryListAppend()
- Promise 객체 리턴하는 함수인데, await을 걸 필요가 없나요?

2021-07-19 13:36 UTC, yjkwon07 commented on src/popup/index.js
> +    EventSetting.categoryCreateEnterEventSetting()
- categoryCreateButtonEventListener 에서 행동하는 로직이 아닌거 같아,, 초기 세팅 영역인 window.addEventListener('DOMContentLoaded', () => { 안에 정의하면 어떨까요?

```js  
    EventSetting.categoryCreateOkEventSetting()
    EventSetting.categoryCreateCancelEventSetting()
    EventSetting.categoryCreateEnterEventSetting()
```

2021-07-19 13:36 UTC, yjkwon07 commented on src/popup/index.js
> +        if (response?.name) {
```js
const response = await APILoad.categoryCreate(categoryName)
const { name } = await APILoad.categoryCreate(categoryName)
```
destructed 구조로 만들어서 if문 체크하는게 어떤가요?

2021-07-19 13:36 UTC, yjkwon07 commented on src/popup/index.js
> +  async categoryCreateOkEventListener(e) {
- categoryCreateEnterEventListener 함수와 같은 의견 사항 입니다.

2021-07-19 13:50 UTC, yjkwon07 approved these changes

2021-07-19 13:50 UTC, yjkwon07 commented on src/popup/index.js
> +      await requestCategoriesRead()
- 여기서 다시 read를 하는것 보다 categoryCreate 호출한 쪽에서 관리를하는게 어떨까요?

2021-07-19 13:50 UTC, yjkwon07 commented on src/popup/index.js
> +      return false
- 이미 requestCategoryCreate에서 로직처리가 이루어졌으면, 해당, categoryCreate, linkWrite 함수는 EventListener에서 관리하는게 맞는거 같네요.

2021-07-19 13:53 UTC, leesoo7595 approved these changes

2021-07-25 13:10 UTC, anxiubin commented on src/popup/index.js
> +          categoryCreateInputWrapperElement +
로그인을 하지 않았을 때는 보여지지 않아야하는 유동적인 성격이 있어서 위와 같은 방식으로 구현했습니다.

2021-07-25 13:33 UTC, anxiubin commented on src/popup/index.js
> +    EventSetting.categoryCreateEnterEventSetting()
만약 `window.addEventListener('DOMContentLoaded', () => ` 이 코드에서 이벤트를 세팅하게 되면`APILoad.categoryListAppend()` 호출을 하면서 새로 돔을 그릴 때 기존 세팅했던 이벤트가 초기화되는 것으로 확인됩니다.
이 부분은 빌드해서 한 번 같이 체크해주시면 좋을 것 같아요!

2021-07-25 14:02 UTC, anxiubin commented on src/popup/index.js
> +      await requestCategoriesRead()
넵 `APILoad.categoryListAppend()` 이 함수를 호출하고 있으므로, `requestCategoriesRead()` 코드는 없애도 될 것 같아요

2021-07-25 14:04 UTC, anxiubin commented on src/popup/index.js
> +          popupMessage({ message: '카테고리가 생성 되었습니다.' })
정확히 어떤 말씀인지 부가 설명 부탁드려요 :(

2021-08-14 05:52 UTC, yjkwon07 commented on src/popup/index.js
> +          popupMessage({ message: '카테고리가 생성 되었습니다.' })
- APILoad에서저 정의한 `create` 같은 `request` 관한 함수는 이미 모듈에서 정의했는데, 다시 한번 정의해서 에러 헨들링을 할 필요가 있을까라는 의문저이 생겼습니다.
- APILoad라는 객체는 조회를 하고 난 후의 액션을 작성했습니다. 즉, 불러오고 붙이는 행위가 반복적으로 보여 만들게 되었습니다. 그 밖의 Create, Update, Delete는 EvenetListiner에서 정의하는게 어떨까 하는 생각을 가지게 되었습니다.
  - 이벤트 마다 다른 행동을 보여야하기 때문에, 각각의 EventListener을 개별적으로 다루는(ex. error)게 적합하다고 생각했습니다.
  
**모든사항은 코드리뷰에서 정리된 상황이므로 Resolve를 하겠습니다.**

2021-08-14 06:08 UTC, yjkwon07 requested changes

2021-08-14 06:18 UTC, anxiubin commented on src/popup/index.js
> +      await requestCategoriesRead()
카테고리를 새로 생성하고 나면 카테고리 리스트를 새로 갱신하고 렌더링해야하기 때문에  `requestCategoriesRead()` 호출이 필요합니다.

2021-08-14 06:19 UTC, yjkwon07 commented on src/popup/index.js
> +          categoryCreateInputWrapperElement +
- `categoryListAppend` 함수의 의미를 정확하게 보여주고자, 조회하고 붙이는 의미로 그 이외의 side-effect를 주는것을 막고 싶었습니다.
- 해당 부분을 `DOMContentLoaded` 상황에서 로그인이 되었을 때, 버튼이 생기도록 코드 위치를 옮기게 되었습니다.

**해당 부분은 코드 리뷰를 통해 협의 되었습니다.**

2021-08-14 06:25 UTC, yjkwon07 commented on src/popup/index.js
> +      await requestCategoriesRead()
궁금한점은 requestCategoriesRead는 조회만 하고 다른 부가적인 행동을 하지 않는데, 지워도 되지 않을까요?

2021-08-14 06:32 UTC, anxiubin commented on src/popup/index.js
> +      await requestCategoriesRead()
앗 그렇네요! 불필요한 호출은 삭제하고 다시 커밋하겠습니다

2021-08-14 07:17 UTC, yjkwon07 commented on src/popup/index.js
> +    EventSetting.categoryCreateEnterEventSetting()
- +버튼을 누를 때마다, 해당 `categoryCreateButtonEventListener` 가 실행되고, categoryCreateInputWrapper show/hide하는것을 확인했습니.
  - APILoad.categoryListAppend가 수정되어 이제는 여기서 정의하는것보다,  window.addEventListener('DOMContentLoaded', () => { 안에 정의 하는것이 더 단일 책임으로 갈 수 있다고 판단 됩니다.
- 추가적으로 EventSetting을 정의하는 시점이 어디서 정의해야할지가 애매한 상황을 자주 접합
- 일단, EvenetListener 안에는 함수의 의미에 맞게 책임을 질 수 있게 하고, 부가적인 행동은 자연스럽게 리스너가 반응할 수 있게 설정하는것이 좋다고 봅니다.

**해당 부분은 코드리뷰로 협의된 사항입니다.**

2021-08-14 07:55 UTC, merged